community_iteminfo = {
    [400177]    = {
        -- Fafnir Helm
        identifiedDescriptionName = {
            "Reduce ACD by 10%",
            "Increase damage of <sk>Dragon's Breath</> and <sk>Dragon's Water Breath</> by 20%",
            "Increase damage of <sk>Storm Blast</> by 30%",
            "Reduce FCT of Nosiege Rune by 100%<lb>",
            "If <sk>Lv. 5 Dragon Training</> is learned,",
            "- MaxHP+ 25%",
            "- MaxSP+ 25%",
            "- Reduce ACD by 20%<lb>",
            "If <sk>Lv. 5 Dragon Howling</> is learned,",
            "- Reduce damage taken from normal and boss class by 20%<lb>",
            "If <sk>Lv. 10 Dragon's Breath</> and <sk>Lv. 10 Dragon's Water Breath</> are learned,",
            "- Increase LRD by 50%",
            "- Reduce FCT of <sk>Dragon's Breath</> and <sk>Dragon's Water Breath</> by 0.2 sec<lb>",
            "<g>When using Turisus Rune</>,",
            "- For 4 minutes, STR+ 30, INT- 30<lb>",
            "<g>When using Isia Rune</>,",
            "- For 5 minutes, Recover 500 HP every 10 seconds<lb>",
            "<g>When using Hagalas Rune</>,",
            "- For 5 minutes, Reflects 10% of incoming melee damage<lb>",
            "<g>When using Asir Rune</>,",
            "- For 5 minutes, ATK+ 10, ASPD+ 10%<lb>",
            "<g>When using Urj Rune</>,",
            "- For 5 minutes, Recover 40 SP every 10 seconds<lb>",
            "<g>When using Rhydo Rune</>,",
            "- For 30 seconds, Resist Knockback<lb>",
            "<g>When using Nosiege Rune</>,",
            "- Recover 100% HP and SP, Cleanses all Masquerade status<lb>",
            "<g>When using Verkana Rune</>,",
            "- Reduce physical damage against all class by 50%",
            "- Reduce LRD by 50%",
            "- MATK- 50%",
            "- Adds a chance to autocast <sk>Lv1. Millenium Shield</>",
            "- Chance to autocast is increased when helmet refinement is above +6 and +8",
            "- <r>This effect does not work in WoE maps</><lb>",
            "<g>For every refine</>,",
            "- Increase resistance to Fire and Water by 3%<lb>",
            "<g>When refined to +6 or higher,</>",
            "- Increase damage of <sk>Storm Blast</> by 20%<lb>",
            "<g>When refined to +7 or higher,</>",
            "- Increase damage of <sk>Dragon's Breath</> and <sk>Dragon's Water Breath</> by 30%<lb>",
            "<g>When refined to +8 or higher,</>",
            "- Increase damage of <sk>Storm Blast</> by 20%<lb>",
            "<g>When refined to +9 or higher,</>",
            "- Increase damage of <sk>Dragon's Breath</> and <sk>Dragon's Water Breath</> by 50%<lb>",
            "Type: <eq>Upper Headgear</>",
            "Defense: <eq>10</>",
            "Weight: <eq>50</>",
            "Required Level: <eq>100</>",
            "Class: <eq>All</>",
        } 
    },
    [450165]    = {
        -- Striking Mail
        identifiedDescriptionName = {
            "All Stats +10<lb>",
            "<pr>Set Bonus",
            "<tl>Striking Mikoshi",
            "Striking Mail</>",
            "<g>For every 3 refine of Striking Mail</>,",
            "- Max HP+ 20%", 
            "- Reduce LRD taken by 5%<lb>",
            "Type: <eq>Armor</>",
            "Defense: <eq>120</>",
            "Weight: <eq>100</>",
            "Required Level: <eq>100</>",
            "Class: <eq>All</>",
        } 
    },
    [470027]    = {
        -- Juggernaut
        identifiedDescriptionName = {
            "MaxHP+ 3%",
            "MaxSP+ 3%",
            "Enables <sk>Lv.1 Improve Concentration</>",
            "Reduce cooldown of <sk>Rich's Coin</> by 3 seconds<lb>",
            "If <sk>Lv.1 Fallen Angel</> is learned,",
            "- ASPD+ 20%",
            "- <sk>Fallen Angel</> SP Cost- 20<lb>",
            "If <sk>Lv.5 Anti-Material Blast</> is learned,",
            "- Ignore DEF against all race by 100%",
            "- When using <sk>God's Hammer</> autocast <sk>Rich's Coin</><lb>",
            "For every Lvl of <sk>Vanishing Buster</>,",
            "- Reduce FCT by 20%",
            "- Increase damage of <sk>Vanishing Buster</> by 60%<lb>",
            "For every Lvl of <sk>Fire Rain</>,",
            "- Increase physical damage against all class by 4%",
            "- Increase damage of <sk>Fire Rain</> by 50%<lb>",
            "For every Lvl of <sk>Howling Mine</>,",
            "- Reduce ACD by 8%",
            "- Increase damage of <sk>Howling Mine</> by 40%<lb>",
            "<g>When refined to +5 or higher,</>",
            "- MaxHP+ 7%",
            "- MaxSP+ 7%<lb>",
            "<g>When refined to +7 or higher,</>",
            "- MaxHP+ 10%",
            "- MaxSP+ 10%<lb>",
            "Type: <eq>Shoes</>",
            "Defense: <eq>12</>",
            "Weight: <eq>40</>",
            "Required Level: <eq>100</>",
            "Class: <eq>All</>",
        }
    },
    [480114]    = {
        -- Striking Mikoshi
        identifiedDescriptionName = {
            "Reduce damage from normal, boss and player class by 5%<lb>",
            "<g>For every refine</>,",
            "- Reduce ACD by 1%",
            "- Increase physical damage against all class by 2%<lb>",
            "<g>When refined to +6 or higher</>,",
            "- ASPD+ 10%",
            "- Perfect Hit+ 25<lb>",
            "<g>When refined to +8 or higher</>,",
            "- Enables <sk>Lv.10 Improve Concentration</>",
            "- If <sk>Lv.10 Improve Concentration</> is learned,",
            "-- ATK+ 50",
            "-- Flee+ 50<lb>",
            "<pr>Set Bonus",
            "<tl>Striking Mikoshi",
            "Striking Hat</>",
            "- Increase LRD by 25%, recover 5 SP per attack<lb>",
            "<pr>Set Bonus",
            "<tl>Striking Mikoshi",
            "Striking Shoes</>",
            "<g>For every 3 refine of Striking Shoes</>,",
            "- All Stats +10<lb>",
            "<pr>Set Bonus",
            "<tl>Striking Mikoshi",
            "Striking Mail</>",
            "<g>For every 3 refine of Striking Mail</>,",
            "- Max HP+ 20%",
            "- Reduce LRD taken by 5%<lb>",
            "Type: <eq>Garment</>",
            "Defense: <eq>40</>",
            "Weight: <eq>40</>",
            "Required Level: <eq>100</>",
            "Class: <eq>All</>",
        } 
    }
}