community_iteminfo = {
    [15376] = {
        -- Illusion Armor Type A
        identifiedDescriptionName = {
            "ATK +100<LB>",
            "E2R",
            "<IND>ATK +10<LB>",
            "@7",
            "<IND>ASPD +10%<LB>",
            "<SB>Illusion Engine Wing Type A</>",
            "<IND>ATK +50<LB>",
            "<SB>Illusion Engine Wing Type B</>",
            "<IND>Reduce ACD by 10%<LB>",
            "<SB>Illusion Leg Type A</>",
            "<IND>ATK +5%<LB>",
            "<SB>Illusion Leg Type B</>",
            "<IND>MaxSP +5%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>105</>",
            "Weight: <EQ>100</>",
            "Required Level: <EQ>130</>",
            "Class: <EQ>All</>",
        }
    },
    [15377] = {
        -- Illusion Armor Type B
        identifiedDescriptionName = {
            "MATK +100<LB>",
            "E2R",
            "<IND>MATK +10<LB>",
            "@7",
            "<IND>Reduce VCT by 10%<LB>",
            "<SB>Illusion Engine Wing Type A</>",
            "<IND>ASPD +10%<LB>",
            "<SB>Illusion Engine Wing Type B</>",
            "<IND>MATK +50<LB>",
            "<SB>Illusion Leg Type A</>",
            "<IND>ASPD +5%<LB>",
            "<SB>Illusion Leg Type B</>",
            "<IND>MATK +5%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>105</>",
            "Weight: <EQ>100</>",
            "Required Level: <EQ>130</>",
            "Class: <EQ>All</>",
        }
    },
    [18851] = {
        -- Red Dragon Plate
        identifiedDescriptionName = {
            "STR +12",
            "MaxHP +15%",
            "MaxSP +10%<LB>",
            "E2R",
            "<IND>ATK +2%",
            "E3R",
            "<IND>Increase physical damage against Dragon race by 7%",
            "@11",
            "<IND>Increase physical damage to Medium and Large Size by 10%",
            "<IND>Reduce FCT by 0.2 sec<LB>",
            "<SB>Dragon Scale Boots",
            "Dragon Scale Hood</>",
            "<IND>ATK +5%",
            "<IND>DEF +50",
            "<IND>MDEF +8",
            "<IND><G>For every 15 base STR</>,",
            "<IND2>ATK +15%",
            "<IND>Chance to trigger <SK>[Dragon's Strength]</> when receiving physical or magical damage</>",
            "<IND2>Chance is increased if base STR is 120 or higher",
            "<IND><G>When the sum of refine is 33 or higher</>,",
            "<IND2>ASPD +20%",
            "<IND2>Reduce ACD by 25%<LB>",
            "<SK>[Dragon's Strength]</>",
            "<G>For 10 seconds</>,",
            "<IND>ATK +10%",
            "<IND><G>If base STR is 120 or higher</>, increase effect to:",
            "<IND2>ATK +25%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>110</>",
            "Weight: <EQ>120</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15392] = {
        -- Green Dragon Plate
        identifiedDescriptionName = {
            "AGI +12",
            "MaxHP +10%",
            "MaxSP +10%<LB>",
            "E2R",
            "<IND>Increase LRD by 2%",
            "E3R",
            "<IND>Increase physical damage against Dragon race by 7%",
            "@11",
            "<IND>Increase physical damage to Medium and Large Size by 10%",
            "<IND>Reduce FCT by 0.2 sec<LB>",
            "<SB>Dragon Scale Boots",
            "Dragon Scale Hood</>",
            "<IND>Increase LRD by 7%",
            "<IND>DEF +50",
            "<IND>MDEF +8",
            "<IND><G>For every 15 base AGI</>,",
            "<IND2>ASPD +4%",
            "<IND>Chance to trigger <SK>[Dragon's Speed]</> when receiving physical or magical damage</>",
            "<IND2>Chance is increased if base AGI is 120 or higher",
            "<IND><G>When the sum of refine is 33 or higher</>,",
            "<IND2>ASPD +20%",
            "<IND2>Reduce ACD by 25%<LB>",
            "<SK>[Dragon's Speed]</>",
            "<G>For 10 seconds</>,",
            "<IND>Increase LRD by 7%",
            "<IND><G>If base AGI is 120 or higher</>, increase effect to:",
            "<IND2>Increase LRD by 17%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>110</>",
            "Weight: <EQ>120</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15393] = {
        -- Gold Dragon Plate
        identifiedDescriptionName = {
            "VIT +12",
            "MaxHP +20%",
            "MaxSP +5%<LB>",
            "E2R",
            "<IND>Reduce VCT by 3%",
            "<IND>ASPD +3%",
            "E3R",
            "<IND>Increase physical and magical damage against Dragon race by 7%",
            "@11",
            "<IND>Increase physical and magical damage to Medium and Large Size by 6%",
            "<IND>Reduce FCT by 0.2 sec<LB>",
            "<SB>Dragon Scale Boots",
            "Dragon Scale Hood</>",
            "<IND>MaxHP +10%",
            "<IND>DEF +80",
            "<IND>MDEF +15",
            "<IND><G>For every 30 base VIT</>,",
            "<IND2>Reduce damage taken from Medium and Large size by 1%",
            "<IND2>Increase CRITD by 3%",
            "<IND>Chance to trigger <SK>[Dragon's Vitality]</> when receiving physical or magical damage</>",
            "<IND2>Chance is increased if base VIT is 120 or higher",
            "<IND><G>When the sum of refine is 33 or higher</>,",
            "<IND2>ASPD +20%",
            "<IND2>Reduce ACD by 25%<LB>",
            "<SK>[Dragon's Vitality]</>",
            "<G>For 10 seconds</>,",
            "<IND>Reduce damage taken from all size by 7%",
            "<IND><G>If base VIT is 120 or higher</>, increase effect to:",
            "<IND2>Reduce damage taken from all size by 12%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>110</>",
            "Weight: <EQ>120</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15394] = {
        -- Purple Dragon Plate
        identifiedDescriptionName = {
            "DEX +12",
            "MaxHP +15%",
            "MaxSP +10%<LB>",
            "E2R",
            "<IND>Reduce VCT by 4%",
            "<IND>ASPD +4%",
            "E3R",
            "<IND>Increase physical and magical damage against Dragon race by 8%",
            "@11",
            "<IND>Increase physical and magical damage to Medium and Large Size by 8%",
            "<IND>Reduce FCT by 0.2 sec<LB>",
            "<SB>Dragon Scale Boots",
            "Dragon Scale Hood</>",
            "<IND>ATK +5%",
            "<IND>MATK +5%",
            "<IND>DEF +50",
            "<IND>MDEF +8",
            "<IND><G>For every 15 base INT</>,",
            "<IND2>ASPD +3%%",
            "<IND2>Reduce VCT by 3%",
            "<IND>Chance to trigger <SK>[Dragon's Dexterity]</> when receiving physical or magical damage</>",
            "<IND2>Chance is increased if base DEX is 120 or higher",
            "<IND><G>When the sum of refine is 33 or higher</>,",
            "<IND2>ASPD +15%",
            "<IND2>Reduce VCT by 15%",
            "<IND2>Reduce ACD by 25%<LB>",
            "<SK>[Dragon's Dexterity]</>",
            "<G>For 10 seconds</>,",
            "<IND>FLEE +50",
            "<IND>Perfect Dodge +10",
            "<IND><G>If base INT is 120 or higher</>, increase effect to:",
            "<IND2>FLEE +80",
            "<IND2>Perfect Dodge +15<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>110</>",
            "Weight: <EQ>120</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15395] = {
        -- Blue Dragon Plate
        identifiedDescriptionName = {
            "INT +12",
            "MaxHP +5%",
            "MaxSP +20%<LB>",
            "E2R",
            "<IND>MATK +2%",
            "<IND>Increase healing effect by 4%",
            "E3R",
            "<IND>Increase magical damage against Dragon race by 7%",
            "@11",
            "<IND>Increase magical damage to Medium and Large Size by 10%",
            "<IND>Reduce FCT by 0.2 sec<LB>",
            "<SB>Dragon Scale Boots",
            "Dragon Scale Hood</>",
            "<IND>MATK +7%",
            "<IND>Increase healing effect by 15%",
            "<IND>DEF +50",
            "<IND>MDEF +8",
            "<IND><G>For every 15 base INT</>,",
            "<IND2>Reduce VCT by 4%",
            "<IND2>Increase CRITD by 3%",
            "<IND>Chance to trigger <SK>[Dragon's Wisdom]</> when receiving physical or magical damage</>",
            "<IND2>Chance is increased if base INT is 120 or higher",
            "<IND><G>When the sum of refine is 33 or higher</>,",
            "<IND2>Reduce VCT by 20%",
            "<IND2>Reduce ACD by 25%<LB>",
            "<SK>[Dragon's Wisdom]</>",
            "<G>For 10 seconds</>,",
            "<IND>Increase magic damage against all element by 20%",
            "<IND>Increase Healing effect by 40%",
            "<IND><G>If base INT is 120 or higher</>, increase effect to:",
            "<IND2>Increase magic damage against all element by 30%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>110</>",
            "Weight: <EQ>120</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15396] = {
        -- Silver Dragon Plate
        identifiedDescriptionName = {
            "LUK +12",
            "MaxHP +15%",
            "MaxSP +15%<LB>",
            "E2R",
            "<IND>CRIT +2",
            "<IND>Increase CRITD by 4%",
            "E3R",
            "<IND>Increase physical damage against Dragon race by 7%",
            "@11",
            "<IND>Increase physical damage to Medium and Large Size by 10%",
            "<IND>Reduce FCT by 0.2 sec<LB>",
            "<SB>Dragon Scale Boots",
            "Dragon Scale Hood</>",
            "<IND>ATK +5%",
            "<IND>DEF +50",
            "<IND>MDEF +8",
            "<IND><G>For every 15 base LUK</>,",
            "<IND2>CRIT +2",
            "<IND2>Increase CRITD by 3%",
            "<IND>Chance to trigger <SK>[Dragon's Luck]</> when receiving physical or magical damage</>",
            "<IND2>Chance is increased if base LUK is 120 or higher",
            "<IND><G>When the sum of refine is 33 or higher</>,",
            "<IND2>ASPD +10%",
            "<IND2>Reduce ACD by 25%<LB>",
            "<SK>[Dragon's Luck]</>",
            "<G>For 10 seconds</>,",
            "<IND>ATK +7%",
            "<IND>Increase CRITD by 7%",
            "<IND><G>If base LUK is 120 or higher</>, increase effect to:",
            "<IND2>ATK +10%",
            "<IND2>Increase CRITD by 10%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>110</>",
            "Weight: <EQ>120</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15397] = {
        -- Soutane of STR
        identifiedDescriptionName = {
            "MaxHP +10%",
            "MaxSP +10%",
            "ASPD +10%<LB>",
            "E2R",
            "<IND>ATK +3%",
            "E3R",
            "<IND>STR +5",
            "E4R",
            "<IND>Increase physical damage against Angel and Devil race by 8%<LB>",
            "<SB>Clergy's Boots",
            "Clergy's Manteau</>",
            "<IND>STR +8",
            "<IND>DEF +30",
            "<IND>MDEF +15",
            "<IND>Reduce damage received from Angel and Devil race by 15%",
            "<IND><G>When the sum of refine is 27 or higher</>,",
            "<IND2>ATK +10%",
            "<IND2>Reduce ACD by 20%",
            "<IND2>Reduce FCT by 20%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>100</>",
            "Weight: <EQ>80</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15398] = {
        -- Soutane of AGI
        identifiedDescriptionName = {
            "MaxHP +10%",
            "MaxSP +10%",
            "ASPD +10%<LB>",
            "E2R",
            "<IND>Increase LRD by 3%",
            "E3R",
            "<IND>AGI +5",
            "E4R",
            "<IND>Increase physical damage against Angel and Devil race by 8%<LB>",
            "<SB>Clergy's Boots",
            "Clergy's Manteau</>",
            "<IND>AGI +8",
            "<IND>DEF +30",
            "<IND>MDEF +15",
            "<IND>Reduce damage received from Angel and Devil race by 15%",
            "<IND><G>When the sum of refine is 27 or higher</>,",
            "<IND2>Increase LRD by 10%",
            "<IND2>Reduce ACD by 20%",
            "<IND2>Reduce FCT by 20%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>100</>",
            "Weight: <EQ>80</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15399] = {
        -- Soutane of VIT
        identifiedDescriptionName = {
            "MaxHP +15%",
            "MaxSP +5%",
            "ASPD +7%<LB>",
            "E2R",
            "<IND>MaxHP +2%",
            "E3R",
            "<IND>VIT +5",
            "E4R",
            "<IND>Increase physical damage against Angel and Devil race by 10%",
            "<IND>Increase magical damage against Angel and Devil race by 10%<LB>",
            "<SB>Clergy's Boots",
            "Clergy's Manteau</>",
            "<IND>VIT +8",
            "<IND>DEF +50",
            "<IND>MDEF +20",
            "<IND>Reduce damage received from Angel and Devil race by 20%",
            "<IND><G>When the sum of refine is 27 or higher</>,",
            "<IND2>ATK +4%",
            "<IND2>MATK +4%",
            "<IND2>Reduce ACD by 20%",
            "<IND2>Reduce FCT by 20%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>100</>",
            "Weight: <EQ>80</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15400] = {
        -- Soutane of DEX
        identifiedDescriptionName = {
            "MaxHP +10%",
            "MaxSP +10%",
            "ASPD +10%",
            "Reduce VCT by 10%<LB>",
            "E2R",
            "<IND>ATK +1%",
            "<IND>MATK +1%",
            "E3R",
            "<IND>DEX +5",
            "E4R",
            "<IND>Increase physical damage against Angel and Devil race by 6%",
            "<IND>Increase magical damage against Angel and Devil race by 6%<LB>",
            "<SB>Clergy's Boots",
            "Clergy's Manteau</>",
            "<IND>DEX +8",
            "<IND>DEF +30",
            "<IND>MDEF +15",
            "<IND>Reduce damage received from Angel and Devil race by 15%",
            "<IND><G>When the sum of refine is 27 or higher</>,",
            "<IND2>ATK +7%",
            "<IND2>MATK +7%",
            "<IND2>Reduce ACD by 20%",
            "<IND2>Reduce FCT by 20%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>100</>",
            "Weight: <EQ>80</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15401] = {
        -- Soutane of INT
        identifiedDescriptionName = {
            "MaxHP +5%",
            "MaxSP +15%",
            "Reduce VCT by 10%<LB>",
            "E2R",
            "<IND>MATK +3%",
            "E3R",
            "<IND>INT +5",
            "E4R",
            "<IND>Increase magical damage against Angel and Devil race by 8%<LB>",
            "<SB>Clergy's Boots",
            "Clergy's Manteau</>",
            "<IND>INT +8",
            "<IND>DEF +30",
            "<IND>MDEF +15",
            "<IND>Reduce damage received from Angel and Devil race by 15%",
            "<IND><G>When the sum of refine is 27 or higher</>,",
            "<IND2>MATK +10%",
            "<IND2>Reduce ACD by 20%",
            "<IND2>Reduce FCT by 20%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>100</>",
            "Weight: <EQ>80</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [15402] = {
        -- Soutane of LUK
        identifiedDescriptionName = {
            "MaxHP +10%",
            "MaxSP +10%",
            "ASPD +10%<LB>",
            "E2R",
            "<IND>CRIT +3",
            "<IND>Increase CRITD by 4%",
            "E3R",
            "<IND>LUK +5",
            "E4R",
            "<IND>Increase physical damage against Angel and Devil race by 8%<LB>",
            "<SB>Clergy's Boots",
            "Clergy's Manteau</>",
            "<IND>LUK +5",
            "<IND>DEF +30",
            "<IND>MDEF +15",
            "<IND>Reduce damage received from Angel and Devil race by 15%",
            "<IND><G>When the sum of refine is 27 or higher</>,",
            "<IND2>ATK +10%",
            "<IND2>Reduce ACD by 20%",
            "<IND2>Reduce FCT by 20%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>100</>",
            "Weight: <EQ>80</>",
            "Required Level: <EQ>170</>",
            "Class: <EQ>All</>",
        }
    },
    [20933] = {
        -- Illusion Engine Wing Type A
        identifiedDescriptionName = {
            "MaxHP +1000<LB>",
            "E2R",
            "<IND>MaxHP +100<LB>",
            "@7",
            "<IND>ASPD +5%<LB>",
            "<SB>Illusion Armor Type A</>",
            "<IND>ATK +50<LB>",
            "<SB>Illusion Armor Type B</>",
            "<IND>ASPD +10%<LB>",
            "<SB>Illusion Leg Type A</>",
            "<IND>Increase CRITD by 10%<LB>",
            "<SB>Illusion Leg Type B</>",
            "<IND>Reduce VCT by 10%<LB>",
            "Type: <EQ>Garment</>",
            "Defense: <EQ>0</>",
            "Weight: <EQ>90</>",
            "Required Level: <EQ>130</>",
            "Class: <EQ>All</>",
        }
    },
    [20934] = {
        -- Illusion Engine Wing Type B
        identifiedDescriptionName = {
            "MaxHP +1000<LB>",
            "E2R",
            "<IND>MaxHP +100<LB>",
            "@7",
            "<IND>Reduce VCT by 5%<LB>",
            "<SB>Illusion Armor Type A</>",
            "<IND>Reduce ACD by 10%<LB>",
            "<SB>Illusion Armor Type B</>",
            "<IND>Increase All Elemental Magic Damage by 10%<LB>",
            "<SB>Illusion Leg Type A</>",
            "<IND>Increase LRD by 5%<LB>",
            "<SB>Illusion Leg Type B</>",
            "<IND>MATK +50<LB>",
            "Type: <EQ>Garment</>",
            "Defense: <EQ>0</>",
            "Weight: <EQ>90</>",
            "Required Level: <EQ>130</>",
            "Class: <EQ>All</>",
        }
    },
    [22196] = {
        -- Illusion Leg Type A
        identifiedDescriptionName = {
            "MaxSP +200<LB>",
            "E2R",
            "<IND>MaxSP +20<LB>",
            "@7",
            "<IND>Increase LRD by 5%<LB>",
            "<SB>Illusion Armor Type A</>",
            "<IND>ATK +5%<LB>",
            "<SB>Illusion Armor Type B</>",
            "<IND>ASPD +5%<LB>",
            "<SB>Illusion Engine Wing Type A</>",
            "<IND>Increase CRITD by 10%<LB>",
            "<SB>Illusion Engine Wing Type B</>",
            "<IND>Increase LRD by 5%<LB>",
            "Type: <EQ>Shoes</>",
            "Defense: <EQ>20</>",
            "Weight: <EQ>50</>",
            "Required Level: <EQ>130</>",
            "Class: <EQ>All</>",
        }
    },
    [22197] = {
        -- Illusion Leg Type B
        identifiedDescriptionName = {
            "MaxSP +200<LB>",
            "E2R",
            "<IND>MaxSP +20<LB>",
            "@7",
            "<IND>Increase All Elemental Magic Damage by 5%<LB>",
            "<SB>Illusion Armor Type A</>",
            "<IND>MaxSP +5%<LB>",
            "<SB>Illusion Armor Type B</>",
            "<IND>MATK +5%<LB>",
            "<SB>Illusion Engine Wing Type A</>",
            "<IND>Reduce VCT by 10%<LB>",
            "<SB>Illusion Engine Wing Type B</>",
            "<IND>Increase All Elemental Magic Damage by 10%<LB>",
            "Type: <EQ>Shoes</>",
            "Defense: <EQ>20</>",
            "Weight: <EQ>50</>",
            "Required Level: <EQ>130</>",
            "Class: <EQ>All</>",
        }
    },
    [400177]    = {
        -- Fafnir Helm
        identifiedDescriptionName = {
            "Reduce ACD by 10%",
            "Increase damage of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 20%",
            "Increase damage of <SK>Storm Blast</> by 30%",
            "Reduce FCT of Nosiege Rune by 100%<LB>",
            "If <SK>Lv. 5 Dragon Training</> is learned,",
            "<IND>MaxHP +25%",
            "<IND>MaxSP +25%",
            "<IND>Reduce ACD by 20%<LB>",
            "If <SK>Lv. 5 Dragon Howling</> is learned,",
            "<IND>RDTF normal and boss class by 20%<LB>",
            "If <SK>Lv. 10 Dragon's Breath</> and <SK>Lv. 10 Dragon's Water Breath</> are learned,",
            "<IND>Increase LRD by 50%",
            "<IND>Reduce FCT of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 0.2 sec<LB>",
            "<G>When using Turisus Rune</>,",
            "<IND>For 4 minutes, STR +30, INT -30<LB>",
            "<G>When using Isia Rune</>,",
            "<IND>For 5 minutes, Recover 500 HP every 10 seconds<LB>",
            "<G>When using Hagalas Rune</>,",
            "<IND>For 5 minutes, Reflects 10% of incoming melee damage<LB>",
            "<G>When using Asir Rune</>,",
            "<IND>For 5 minutes, ATK +10, ASPD +10%<LB>",
            "<G>When using Urj Rune</>,",
            "<IND>For 5 minutes, Recover 40 SP every 10 seconds<LB>",
            "<G>When using Rhydo Rune</>,",
            "<IND>For 30 seconds, Resist Knockback<LB>",
            "<G>When using Nosiege Rune</>,",
            "<IND>Recover 100% HP and SP, Cleanses all Masquerade status<LB>",
            "<G>When using Verkana Rune</>,",
            "<IND>Reduce physical damage against all class by 50%",
            "<IND>Reduce LRD by 50%",
            "<IND>MATK- 50%",
            "<IND>Adds a chance to autocast <SK>Lv1. Millenium Shield</>",
            "<IND>Chance to autocast is increased when helmet refinement is above +6 and +8",
            "<IND><R>This effect does not work in WoE maps</><LB>",
            "ER",
            "<IND>Reduce damage received from Fire and Water elements by 3%<LB>",
            "@6",
            "<IND>Increase damage of <SK>Storm Blast</> by 20%<LB>",
            "@7",
            "<IND>Increase damage of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 30%<LB>",
            "@8",
            "<IND>Increase damage of <SK>Storm Blast</> by 20%<LB>",
            "@9",
            "<IND>Increase damage of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 50%<LB>",
            "Type: <EQ>Upper Headgear</>",
            "Defense: <EQ>10</>",
            "Weight: <EQ>50</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        } 
    },
    [450165]    = {
        -- Striking Mail
        identifiedDescriptionName = {
            "All Stats +10<LB>",
            "<SB>Striking Mikoshi</>",
            "E3ROStriking Mail</>,",
            "<IND>Max HP +20%", 
            "<IND>Reduce LRD taken by 5%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>120</>",
            "Weight: <EQ>100</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        } 
    },
    [470027]    = {
        -- Juggernaut
        identifiedDescriptionName = {
            "MaxHP +3%",
            "MaxSP +3%",
            "Enables <SK>Lv.1 Improve Concentration</>",
            "Reduce cooldown of <SK>Rich's Coin</> by 3 seconds<LB>",
            "If <SK>Lv.1 Fallen Angel</> is learned,",
            "<IND>ASPD +20%",
            "<IND><SK>Fallen Angel</> SP Cost- 20<LB>",
            "If <SK>Lv.5 Anti-Material Blast</> is learned,",
            "<IND>Ignore DEF against all race by 100%",
            "<IND>When using <SK>God's Hammer</> autocast <SK>Rich's Coin</><LB>",
            "For every Lvl of <SK>Vanishing Buster</>,",
            "<IND>Reduce FCT by 20%",
            "<IND>Increase damage of <SK>Vanishing Buster</> by 60%<LB>",
            "For every Lvl of <SK>Fire Rain</>,",
            "<IND>Increase physical damage against all class by 4%",
            "<IND>Increase damage of <SK>Fire Rain</> by 50%<LB>",
            "For every Lvl of <SK>Howling Mine</>,",
            "<IND>Reduce ACD by 8%",
            "<IND>Increase damage of <SK>Howling Mine</> by 40%<LB>",
            "@5",
            "<IND>MaxHP +7%",
            "<IND>MaxSP +7%<LB>",
            "@7",
            "<IND>MaxHP +10%",
            "<IND>MaxSP +10%<LB>",
            "Type: <EQ>Shoes</>",
            "Defense: <EQ>12</>",
            "Weight: <EQ>40</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        }
    },
    [480114]    = {
        -- Striking Mikoshi
        identifiedDescriptionName = {
            "RDTF normal and boss class by 5%",
            "RDTF player races by 5%<LB>",
            "ER",
            "<IND>Reduce ACD by 1%",
            "<IND>Increase physical damage against all class by 2%<LB>",
            "@6",
            "<IND>ASPD +10%",
            "<IND>Perfect Hit +25<LB>",
            "@8",
            "<IND>Enables <SK>Lv.10 Improve Concentration</>",
            "<IND>If <SK>Lv.10 Improve Concentration</> is learned,",
            "<IND2>ATK +50",
            "<IND2>Flee +50<LB>",
            "<SB>Striking Hat</>",
            "<IND>Increase LRD by 25%",
            "<IND>Recover 5 SP per attack<LB>",
            "<SB>Striking Shoes</>",
            "E3ROStriking Shoes</>,",
            "<IND>All Stats +10<LB>",
            "<SB>Striking Mail</>",
            "E3ROStriking Mail</>,",
            "<IND>Max HP +20%",
            "<IND>Reduce LRD taken by 5%<LB>",
            "Type: <EQ>Garment</>",
            "Defense: <EQ>40</>",
            "Weight: <EQ>40</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        } 
    },
    [490208] = {
        -- Memento Mori
        identifiedDescriptionName = {
            "All Stats +10",
            "Reduce ACD by 10%",
            "Increase physical damage against all size by 10%",
            "Increase magical damage against all size by 10%<LB>",
            "Type: <EQ>Accessory</>",
            "Defense: <EQ>0</>",
            "Weight: <EQ>10</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        }
    },
}