community_iteminfo = {
    [400177]    = {
        -- Fafnir Helm
        identifiedDescriptionName = {
            "Reduce ACD by 10%",
            "Increase damage of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 20%",
            "Increase damage of <SK>Storm Blast</> by 30%",
            "Reduce FCT of Nosiege Rune by 100%<LB>",
            "If <SK>Lv. 5 Dragon Training</> is learned,",
            "- MaxHP+ 25%",
            "- MaxSP+ 25%",
            "- Reduce ACD by 20%<LB>",
            "If <SK>Lv. 5 Dragon Howling</> is learned,",
            "- Reduce damage taken from normal and boss class by 20%<LB>",
            "If <SK>Lv. 10 Dragon's Breath</> and <SK>Lv. 10 Dragon's Water Breath</> are learned,",
            "- Increase LRD by 50%",
            "- Reduce FCT of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 0.2 sec<LB>",
            "<G>When using Turisus Rune</>,",
            "- For 4 minutes, STR+ 30, INT- 30<LB>",
            "<G>When using Isia Rune</>,",
            "- For 5 minutes, Recover 500 HP every 10 seconds<LB>",
            "<G>When using Hagalas Rune</>,",
            "- For 5 minutes, Reflects 10% of incoming melee damage<LB>",
            "<G>When using Asir Rune</>,",
            "- For 5 minutes, ATK+ 10, ASPD+ 10%<LB>",
            "<G>When using Urj Rune</>,",
            "- For 5 minutes, Recover 40 SP every 10 seconds<LB>",
            "<G>When using Rhydo Rune</>,",
            "- For 30 seconds, Resist Knockback<LB>",
            "<G>When using Nosiege Rune</>,",
            "- Recover 100% HP and SP, Cleanses all Masquerade status<LB>",
            "<G>When using Verkana Rune</>,",
            "- Reduce physical damage against all class by 50%",
            "- Reduce LRD by 50%",
            "- MATK- 50%",
            "- Adds a chance to autocast <SK>Lv1. Millenium Shield</>",
            "- Chance to autocast is increased when helmet refinement is above +6 and +8",
            "- <R>This effect does not work in WoE maps</><LB>",
            "<G>For every refine</>,",
            "- Increase resistance to Fire and Water by 3%<LB>",
            "<G>When refined to +6 or higher,</>",
            "- Increase damage of <SK>Storm Blast</> by 20%<LB>",
            "<G>When refined to +7 or higher,</>",
            "- Increase damage of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 30%<LB>",
            "<G>When refined to +8 or higher,</>",
            "- Increase damage of <SK>Storm Blast</> by 20%<LB>",
            "<G>When refined to +9 or higher,</>",
            "- Increase damage of <SK>Dragon's Breath</> and <SK>Dragon's Water Breath</> by 50%<LB>",
            "Type: <EQ>Upper Headgear</>",
            "Defense: <EQ>10</>",
            "Weight: <EQ>50</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        } 
    },
    [450165]    = {
        -- Striking Mail
        identifiedDescriptionName = {
            "All Stats +10<LB>",
            "<PR>Set Bonus",
            "<TL>Striking Mikoshi",
            "Striking Mail</>",
            "<G>For every 3 refine of Striking Mail</>,",
            "- Max HP+ 20%", 
            "- Reduce LRD taken by 5%<LB>",
            "Type: <EQ>Armor</>",
            "Defense: <EQ>120</>",
            "Weight: <EQ>100</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        } 
    },
    [470027]    = {
        -- Juggernaut
        identifiedDescriptionName = {
            "MaxHP+ 3%",
            "MaxSP+ 3%",
            "Enables <SK>Lv.1 Improve Concentration</>",
            "Reduce cooldown of <SK>Rich's Coin</> by 3 seconds<LB>",
            "If <SK>Lv.1 Fallen Angel</> is learned,",
            "- ASPD+ 20%",
            "- <SK>Fallen Angel</> SP Cost- 20<LB>",
            "If <SK>Lv.5 Anti-Material Blast</> is learned,",
            "- Ignore DEF against all race by 100%",
            "- When using <SK>God's Hammer</> autocast <SK>Rich's Coin</><LB>",
            "For every Lvl of <SK>Vanishing Buster</>,",
            "- Reduce FCT by 20%",
            "- Increase damage of <SK>Vanishing Buster</> by 60%<LB>",
            "For every Lvl of <SK>Fire Rain</>,",
            "- Increase physical damage against all class by 4%",
            "- Increase damage of <SK>Fire Rain</> by 50%<LB>",
            "For every Lvl of <SK>Howling Mine</>,",
            "- Reduce ACD by 8%",
            "- Increase damage of <SK>Howling Mine</> by 40%<LB>",
            "<G>When refined to +5 or higher,</>",
            "- MaxHP+ 7%",
            "- MaxSP+ 7%<LB>",
            "<G>When refined to +7 or higher,</>",
            "- MaxHP+ 10%",
            "- MaxSP+ 10%<LB>",
            "Type: <EQ>Shoes</>",
            "Defense: <EQ>12</>",
            "Weight: <EQ>40</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        }
    },
    [480114]    = {
        -- Striking Mikoshi
        identifiedDescriptionName = {
            "Reduce damage from normal, boss and player class by 5%<LB>",
            "<G>For every refine</>,",
            "- Reduce ACD by 1%",
            "- Increase physical damage against all class by 2%<LB>",
            "<G>When refined to +6 or higher</>,",
            "- ASPD+ 10%",
            "- Perfect Hit+ 25<LB>",
            "<G>When refined to +8 or higher</>,",
            "- Enables <SK>Lv.10 Improve Concentration</>",
            "- If <SK>Lv.10 Improve Concentration</> is learned,",
            "-- ATK+ 50",
            "-- Flee+ 50<LB>",
            "<PR>Set Bonus",
            "<TL>Striking Mikoshi",
            "Striking Hat</>",
            "- Increase LRD by 25%, recover 5 SP per attack<LB>",
            "<PR>Set Bonus",
            "<TL>Striking Mikoshi",
            "Striking Shoes</>",
            "<G>For every 3 refine of Striking Shoes</>,",
            "- All Stats +10<LB>",
            "<PR>Set Bonus",
            "<TL>Striking Mikoshi",
            "Striking Mail</>",
            "<G>For every 3 refine of Striking Mail</>,",
            "- Max HP+ 20%",
            "- Reduce LRD taken by 5%<LB>",
            "Type: <EQ>Garment</>",
            "Defense: <EQ>40</>",
            "Weight: <EQ>40</>",
            "Required Level: <EQ>100</>",
            "Class: <EQ>All</>",
        } 
    }
}